version: "3.8"

services:
  nginx:
    image: ashs26/philchar-nginx-app:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "80:80"

  client:
    image: ashs26/philchar-client-app:client-latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_RAZORPAY_KEY=${REACT_APP_RAZORPAY_KEY}

  server:
    image: ashs26/philchar-server-app:server-latest
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - RAZORPAY_KEY=${RAZORPAY_KEY}
      - RAZORPAY_SECRET=${RAZORPAY_SECRET}
