version: "3.8"

services:
  nginx:
    image: ashs26/philchar-nginx-app:nginx-latest
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "8080:80"

  client:
    image: ashs26/philchar-client-app:client-latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_BACKEND_URL=/server/
      - REACT_APP_RAZORPAY_KEY=rzp_test_VioGN9w52CWjOI
      - REACT_APP_CHAT_HOST=/server/

  server:
    image: ashs26/philchar-server-app:server-latest
    environment:
      - MONGODB_URL=mongodb+srv://sahildharme8:Q2ZtYUARtw1t4izZ@ngodata.vnkhaih.mongodb.net/?retryWrites=true&w=majority
      - MONGODB_PASSWORD=sahildharme8
      - MONGODB_USERNAME=Q2ZtYUARtw1t4izZ
      - RAZORPAY_KEY=rzp_test_VioGN9w52CWjOI
      - RAZORPAY_SECRET=c77bQPBng9RtzOAKTMLI3W5y
      - ORIGIN=http://localhost:3000/
